### PR TITLE
[DRAFT] Ignore Pattern for file count

### LINKED ISSUE #70: Add possibility to ignore deleted files in certain locations
I'd love to see a feature where I can specify files / folders (or a regular expression) which should not count to the deleted file count. But are still synced (so I can't use the SnapRAID exclude feature).

I know that this also means, that the script will have to parse the output of the diff instead of just reading the summary.

Why would I need something like this?

I have a rolling backup running onto my SnapRAID, certain parts will get deleted after a day or two and new things will pop up. This is a mess with counting the deleted files, you never know how much it'll be and honestly I don't really care. Of course someone could just delete my whole backup and the sync would just continue when the backup is excluded from counting, but that is a risk I'll take over just setting the delete count to 1000 and miss that I deleted the wrong folder in some after work delirium.

### PR DESCRIPTION
**Pull request by Wastus**
This is a solution to fix #70.
It's not pretty but it works, though users should test the pattern thoroughly to not exclude to many items.

I've done some rudimentary tests.

### CODE REVIEW

**Comment by tehniemer** [comment]
@auanasgheps did you mean to close this?

**Comment by auanasgheps** [comment]
I did not close this. But got deleted automatically as dev branch got merged into main.

**Comment by tehniemer** [comment]
This was closed again when `dev` was merged. 

I have been testing this for a while now and it seems to be working as intended.

**Comment by auanasgheps** [comment]
Apologies, It gets closed automatically when I push dev to master.

@tehniemer do you think we should make it better?

**Comment by auanasgheps** [comment]
Ok, maybe I got it: using the example as a reference, the number of the matches is the number of files that will be included after the filter.

If I enter `*.mkv` in the filter I get 8 matches, none of the matched files contains *.mkv (are 2, which are excluded)

**Comment by tehniemer** [comment]
I've been running with this feature for quite a while now and it's been pretty great at filtering out noise from locations that have frequent changes like borg backup and proxmox backup server directories. I have added some additional functionality to my version to log the ignored file count, which is nice to see IMO. 

I'm not sure how to properly indicate the changes I made in this PR, so I'll just link to my [fork](https://github.com/tehniemer/snapraid-aio-script/blob/dev/snapraid-aio-script.sh) for review.

**Comment by auanasgheps** [comment]
Hi @tehniemer, I would definitely consider your work which logs the ignored file count.

You can make another PR to this repo and we'll mention that @Wastus did the original work

**Comment by auanasgheps** [comment]
I had a look at it, it looks super clean :)

**Pull request closed without merging**
