### PR TITLE
Add hooks to pause docker containers before running

### PR DESCRIPTION
**Pull request by tehniemer**
I've been using this in my personal copy and find that it works well to pause services that may modify files during a diff/sync/scrub.

### CODE REVIEW

**Comment by auanasgheps** [comment]
Hi,
Is this code updated compared to the original from Zack Reed? I've never used it but I read is quite buggy.

**Comment by tehniemer** [comment]
I reworked it and have been using it to control remote containers for over a year and I've had no issues with it. If a service doesn't exist or is unable to be paused for some reason, the script reports the error but continues running and completes as expected. It may be helpful to add some extra instructions around it in the readme file as for how to set up passwordless SSH connections.

**Comment by auanasgheps** [comment]
Thank you. I don't think many would be interested in SSH connections, let's keep it simple.

I will merge once I have time to doublecheck.

**Comment by tehniemer** [comment]
You're probably right, that's why I made it a selectable option.

**Comment by auanasgheps** [comment]
Looks good to me, I'm merging to dev.
Thanks for your contribution, I hope will work fine :)

**Pull request merged**
