### PR TITLE
[Feature] Add from address to email notification and a user-created script instead of the default email

### PR DESCRIPTION
**Pull request by Caedis**
The from address addition is straight forward.

The user-created script gets the subject and body (in that order) so that the user can do whatever they want with it and without editing the main script.

Sorry for the whitespace fixes, if needed, I can diff and patch them out.

### CODE REVIEW

**Comment by auanasgheps** [comment]
Hello! Thanks for the contribution!

Space fixes are minor but definitely appreciated.

What is the goal of the user script? To use an external notification system? Can you provide some real life examples?

The user can already configure a different mail binary in the config file.

**Comment by Caedis** [comment]
While being able to change the mail binary, you can not change the parameters that is passed to it, so you would have to use something is works with everything that is passed in.  

An example would be:  

HOOK_NOTIFICATION="$CURRENT_DIR/email_script.sh"

email_script.sh:  

    curl -s --user 'api:my_api_key' \
	https://api.mailgun.net/v3/my_domain/messages \
    -F from=from_address \
    -F to=to_address \
    -F subject="$1" \
    -F text="$2"

**Comment by Caedis** [comment]
need to make a couple changes

**Comment by auanasgheps** [comment]
> While being able to change the mail binary, you can not change the parameters that is passed to it, so you would have to use something that works with everything that is passed in.
> 
> An example would be:
> 
> HOOK_NOTIFICATION="$CURRENT_DIR/email_script.sh"
> 
> email_script.sh:

Allright, It makes sense now :)



> need to make a couple changes

No problem. Let me know when ready

**Comment by Caedis** [comment]
Feel free to make any changes before merging

**Comment by auanasgheps** [comment]
@Caedis I merged a PR created before yours. These are small changes and they do not interfere with yours, but there are some conflicts according to GitHub.
Can you rebase your changes based on the current versions? I won't make other changes, I promise!

**Comment by Caedis** [comment]
Can do

**Comment by Caedis** [comment]
There we go....i need more experience with rebasing

**Comment by auanasgheps** [comment]
Looks good now!

**Pull request merged**
