### PR TITLE
Changed pause/unpause to stop/start docker containers to fix errors, other minor fixes as well.

### PR DESCRIPTION
**Pull request by tehniemer**

### CODE REVIEW

**Comment by auanasgheps** [comment]
Hey, thanks for making more commits! I can see some fixes here and there. That' good you tested, since I'm not using containers on my SnapRAID array. 

I need to merge this with the dev branch, hoping for no conflictual changes.

**Comment by auanasgheps** [comment]
Ok, I've rebased the PR to the new dev branch, so I can have a look at the actual conflicts. Will do this soon.
PS: Since there are a lot of changes I think we can go for a 3.0 release when ready ;)

**Comment by tehniemer** [comment]
I changed to docker stop because I started to get a lot of errors like this:
```
Pausing Service - Amtd bazarr filebot filerun lazylibrarian lidarr mylar nzbget podgrab qbittorrent radarr readarr sabnzbd sonarr syncthing ubooquity
amtd
bazarr
filerun
mylar
nzbget
podgrab
ubooquity
Error response from daemon: Cannot pause container fd41d0d7ab0799eaf41c2e7ce7ad32178f0b1d88e3f279be135abdc2af5e0e62: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 87b3e7cc92a828ab6b11b255001370fb100884dee020397e2ccbb66abc0a024d: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 0897c33972c555b2720030905a00730a0b09af2bcbcdb0a780eb28c5e23e3a9c: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 0d33ab600b305f7bc9976f48dad2e54e34d1ab9587b45741ea627099959e2525: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 34d108ad46b3c6ef733ff83ed8114090d659b00506677fec119909235110b78f: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container f6076e6a9a3b11381228e10c3a436743740c1c9a7240d93817104ba97bfe14bd: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 1ddfb0aaab35baa38ee2abf0383cf1d4c16f735b26c2d618501fea1d7dd9c2b8: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 9def4bcf176db9aefb3721725c9c0d7877fffff2c60472dfcbcf205bd141bf88: OCI runtime pause failed: unable to freeze: unknown
Error response from daemon: Cannot pause container 2d3124997d19275a4af322aa58e04ba7eb7dae8222b995dd69d274211df69ff8: OCI runtime pause failed: unable to freeze: unknown
```
It was working with pause for a very long time but recently quit and I haven't been able to pinpoint the reason. Stop has been behaving for me with no drawback in my setup. Maybe we could make stop or pause a selectable option in the config?

**Comment by tehniemer** [comment]
I was also having problems with `get_count` for some reason erroring out like this so that's why that change is there, not sure if it could be fixed another way.
```
DIFF finished [Wed 07 Apr 2021 12:03:04 AM CDT]
ERROR - failed to get one or more count values. Unable to proceed.
```

**Comment by tehniemer** [comment]
I just found a syntax error in my script and corrected it in my master branch, does that automatically update this pull request or is there something else I have to do to include that update here? I haven't done much collaboration on github before.

**Comment by auanasgheps** [comment]
The update has appeared here, but I still need to do a manual merge.

**Comment by auanasgheps** [comment]
Would you like to try an alternative pause fix?
Last year a user `https://zackreed.me/snapraid-split-parity-sync-script/#comment-319` has posted a fix about docker management. 
I can create an alternative branch and implement the proposed changes (from the actual dev, not merging your recent changes)

**Comment by tehniemer** [comment]
I believe that is a different issue than what I was experiencing. Mine was unable to pause the containers, the issue in that thread seems that the script tries to unpause twice.

**Comment by auanasgheps** [comment]
@tehniemer I was doing some testing with your code and bumped in a issue. If I configure more than one container to be stopped, the script does not handle it correctly. 
The funny thing is the code runs correctly if I create a script that does only that.
Have you seen this before?

**Comment by tehniemer** [comment]
I have not run into any issues yet, I use the script as I have modified it with the list of containers in my example above without error. Wonder if it's a docker version thing?

**Comment by auanasgheps** [comment]
I'm using Docker 20.10.5, what about you?

**Comment by auanasgheps** [comment]
I'm going crazy.

If I do this simple script, works fine.
```bash
#!/bin/bash
SERVICES="code-server filebrowser"
MANAGE_SERVICES=1

function main(){
  if [ $MANAGE_SERVICES -eq 1 ]; then
    echo
    echo "###Pause Containers [`date`]"
	pause_services
  fi
 }
 
function pause_services(){
      echo "Stopping Services: $SERVICES";
      docker pause $SERVICES
}
main "$@"
```
The output is correct and pauses containers:
```markdown
###Pause Containers [Fri  9 Apr 16:32:12 CEST 2021]
Stopping Services: code-server filebrowser
code-server
filebrowser
```


However f I use this code inside the main script, I get this:
```markdown
###Pause Containers [Fri 9 Apr 16:34:03 CEST 2021]
Stopping Services: code-server filebrowser
Error response from daemon: No such container: code-server filebrowser
```

I'm calling the command correctly and the variable is parsed too, I verified this by adding a dumb echo `"I am going to run: docker pause $SERVICES";` and the output is correct.

**Comment by tehniemer** [comment]
> I'm using Docker 20.10.5, what about you?

Same version here, have you tried running my modified script with no additional edits as a test?

**Comment by auanasgheps** [comment]
Yes. This is the version

**Comment by auanasgheps** [comment]
Yes. I took again the script from this PR and run it:

```markdown
Stop Services [Fri 9 Apr 16:50:12 CEST 2021]
Setting up service array
Stopping Service - Code-server filebrowser
Error response from daemon: No such container: code-server filebrowser
```

**Comment by auanasgheps** [comment]
Either way I've got an alternative: simply pause/stop **all** running containers. 
This one works because it's a command that does not read another variable.

How would you feel about this? Maybe we could restart containers aftert SYNC is completed so they paused/stopped only when sync is running.

**Comment by tehniemer** [comment]
Do you use docker-compose? How are you creating those containers? There are two "container names" and if you use the wrong one I could see this not working. For example
```
## Plex Meta Manager - PLEX collection creation tool
  pmm:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - '$DOCKER_DIR/pmm:/config'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
#      PMM_RUN: 'true'
      PMM_TIME: '10:00'
```
If I ran this script and called `pmm` it will not work, but if I called `plex-media-manager` it will.

**Comment by auanasgheps** [comment]
I am using docker-compose, but I am calling the real container name.
If I use the same code in a simpler script, I can pause container without errors. When the script is running is throwing the error, but does not really make sense to me

**Comment by tehniemer** [comment]
Very bizarre indeed, nothing obvious is popping in my head. I'll keep thinking about it.

**Comment by auanasgheps** [comment]
Ok what I will do now is merge your changes **EXCEPT** Docker management, which I will remove entirely, at least for now. 
You made many other good changes so at least I can commit those.

**Comment by auanasgheps** [comment]
Ouch, if I resolve the conflict changes I will commit to your master repo, I don't even know if I'm allowed to do this. 

Since I will be removing part of your work, make at least a copy of your branch. The good news is that will be rebased on the latest changes.

**Comment by auanasgheps** [comment]
Hey, there's another chap who just opened a PR #6 who is fixing indentation/comments without making changes to docker management.

My plan is to merge his PR (just because it's easier and I don't have to make further changes), then work on container handling with your work. I think I can also introduce an option to stop or pause containers, so the user has a choice.

This means your repo soon won't be in sync with this one, but I will still be able to use your code and obviously mention you. Either way you are in the [credits](https://github.com/auanasgheps/snapraid-aio-script/commit/1be66705f65a5ad0c1ab42f3c0bf1faab7442592)

BTW I still need to fix the error I mentioned above regarding multiple containers.

So I will close this PR but we'll be in touch!

**Comment by auanasgheps** [comment]
Update:
A friend of mine helped and fixed the issue I was facing. I will add your code soon!

**Comment by tehniemer** [comment]
That's great news!

**Comment by auanasgheps** [comment]
Some code is already in "docker-old-base" (old because it's not nicely formatted as the master, because is based off the 2.8 version)

I've added remote docker (from yours), plus
- Docker mode option, choose between docker pause and docker stop.
- Validate docker all docker configuration (containers and docker mode) before running
   - Do not output docker headers if verification has failed

It's working really well (I tested all combinations), but I'll need some time to merge it to master.

Meanwhile, `get_counts` change is in master!

**Comment by tehniemer** [comment]
Nice to hear I helped a little, look forward to checking out these Docker changes!

**Pull request closed without merging**
