### PR TITLE
Feat: Add Custom Hook

### PR DESCRIPTION
**Pull request by nzlov**
No Test...
Sync no over. Please wait...

#26

### CODE REVIEW

**Comment by auanasgheps** [comment]
No problem, take your time and let me know when is completed.

**Comment by nzlov** [comment]
left 2h.

**Comment by nzlov** [comment]
Verification passed, you can merge now.

**Comment by auanasgheps** [comment]
Thanks @nzlov.
I will merge this after the other PR, where I'm waiting an answer. 
That one is bigger and I want to do things in order.

**Comment by auanasgheps** [comment]
Will merge and and make some adjustments.
Thank you!

**Pull request merged**
